### ISSUE TITLE
shutil.SameFileError -- are the same file

### ISSUE THREAD

**Issue by monajalal** [ponimatkin/focalpose#6] opened 2023-02-14 16:03 UTC
I get the following error when running this:

```
(focalpose) mona@ard-gpu-01:~/focalpose$ bash preprocess_data.sh

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/cars_to_urdf.py", line 74, in <module>
    copy2(obj.as_posix(), obj.with_name(f'{cls.name}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj' and PosixPath('/home/mona/focalpose/local_data/StanfordCars/models/eaeabed4e984364868ebd0cfefbb61e9/eaeabed4e984364868ebd0cfefbb61e9.obj') are the same file
Setting OMP and MKL num threads to 1.
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mona/focalpose/focalpose/scripts/pix3d_to_urdf.py", line 77, in <module>
    copy2(files.as_posix(), files.with_name(f'{obj.name}_{cls.name.upper()}').with_suffix('.obj'))
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/mona/anaconda3/envs/focalpose/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj' and PosixPath('/home/mona/focalpose/local_data/pix3d/model/tool/SS_3/SS_3_TOOL.obj') are the same file
Setting OMP and MKL num threads to 1.
```
This error is caused since initially I ran this error I didn't have `xvfb`, then I got error (`xfvb not found`) and installed it using `sudo apt-get install xvfb` and reran the script.

**Comment by ponimatkin** [comment] 2023-02-14 21:03
Closed as it is duplicate of https://github.com/ponimatkin/focalpose/issues/8.

**Closed by ponimatkin** 2023-02-14 21:03 UTC
